spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://122.51.4.113:3306/demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: super_mybatis
    password: 323ba860e23d4982a9a4c978c8752eaa
  # redis相关配置
  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）默认是2000ms
    timeout: 2000ms
  cache:
    redis:
      ## Entry expiration in milliseconds. By default the entries never expire.
      time-to-live: 1d
      #写入redis时是否使用键前缀。
      use-key-prefix: true

super-mybatis:
  global-setting:
    #开启debug日志
    debug: true
    database-setting:
      camel-model: true
      upper-case-mode: true
      table-perfix: test_
      show-sql: true
      primary-key-type: auto
    snowflake-setting:
      datacenter-id: 1
      worker-id: 1

    db-cache-setting:
      cache-switch: true
      db-cache-type: Redis
      redis-host: 122.51.4.113
      redis-port: 16379
      redis-pwd: caijie888
