spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 111111

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

super-mybatis:
  global-setting:
    #开启debug日志
    debug: true
    database-setting:
      primary-key-type: auto
      camel-model: true
      upper-case-mode: true
      table-perfix: test_
      show-sql: true
    snowflake-setting:
      datacenter-id: 1
      worker-id: 1


    db-cache-setting:
      cache-switch: true
      db-cache-type: redis

