spring:
  application:
    name: demo
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1u9vqxg28tqx9ftgo.mysql.rds.aliyuncs.com/super-mybatis?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: dev
    password: dev@1234
super-mybatis:
  datasource:
    pool:
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 5
      maxActive: 20
      maxWait: 60000
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100
      validationQuery: SELECT 1 FROM DUAL
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      filters: stat,wall
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://rm-bp1u9vqxg28tqx9ftgo.mysql.rds.aliyuncs.com/super-mybatis?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
      username: dev
      password: dev@1234
    slave1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://rm-bp1u9vqxg28tqx9ftgo.mysql.rds.aliyuncs.com/super-mybatis-demo?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
      username: dev
      password: dev@1234
  global-setting:
    #开启debug日志
    debug: true
    database-setting:
      camel-model: true
      upper-case-mode: true
      table-perfix: test_
      show-sql: true
      primary-key-type: auto
      tenant: true
    snowflake-setting:
      datacenter-id: 1
      worker-id: 1

    db-cache-setting:
      cache-switch: true
      db-cache-type: Redis
      redis-host: 122.51.4.113
      redis-port: 16379
      redis-pwd: caijie888
